apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprinboot_postgres
  labels:
    app: sprinboot_postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprinboot_postgres
  template:
    metadata:
      labels:
        app: sprinboot_postgres
    spec:
      containers:
        - name: sprinboot_postgres
          image: 304520711562.dkr.ecr.us-east-1.amazonaws.com/mydemorepoecr:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
