apiVersion: v1
kind: Service
metadata:
  name: springboot-postgres
spec:
  selector:
    app: springboot-postgres
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
