apiVersion: v1
kind: Service
metadata:
  name: springboot-postgres
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80  # Adjust to match your application's container port
      protocol: TCP
  selector:
    app: springboot-postgres  # Ensure this matches the labels of your Deployment or Pods