apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp
  labels:
    app: usermgmt-restapp
spec:
  type: ClusterIP
  selector:
    app: usermgmt-restapp
  ports:
    - port: {{ .Values.usermgmt.servicePort }}
      targetPort: {{ .Values.usermgmt.servicePort }}
